export type Language = 'python'
                        | 'water'
                        | 'bug'
                        | 'normal'
                        | 'grass'
                        | 'fighting'
                        | 'electric'
                        | 'kotlin'
                        | 'html'
                        | 'css'
                        | 'javascript'
                        | 'typescript'
                        | 'react'
                        | 'vue'
                        | 'js'
                        | 'ts';

